spring:
  datasource:
    password: secret
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/captest
    username: postgres
  config:
    activate:
      on-profile: default
cds:
  data-source:
    auto-config:
      enabled: true
